baseURL = "https://irfansharif.io/blog/"
canonifyURLs = "true"
languageCode = "en-us"
theme = "central"
title = "irfansharif.io"
footnoteReturnLinkContents = "⤻" # Options: ↩
googleAnalytics = "UA-92294257-1"

[permalinks]
  posts = "/:title/"
  page = "/:slug/"

# Theme variables.
[params]
  title = "irfansharif.io"
  description = "Notes on engineering for young(er) bloods."
  summary = "Notes on engineering for young(er) bloods."

[markup]
  defaultMarkdownHandler = "blackfriday"

# vim: ts=2 sw=2 et ft=conf
