builddrafts = true 
canonifyurls = true
relativeURLS = true
config = "config.toml"
defaultextension = "html"
defaultlayout = "post"

baseurl = "https://irfansharif.github.io/blog/"
title = "Irfan Sharif"
languageCode = "en-us"
buildDrafts = true
defaultContentLanguage = "en"
enableRobotsTXT = true
disable404 = false
editor = "vim"
googleAnalytics = "UA-92294257-1"
paginate = 5
paginatePath = "page"
preserveTaxonomyNames = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsUseClasses = true
theme = "meta"
uglyURLS = false
disablePathToLower = false
watch = true

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  copyrightHolder = "Irfan Sharif"
  showPoweredBy = true

# -----------------------------------------------------------------------
# Morphism theme navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "home"
  url = "/"

[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"

[[menu.nav]]
  name = "Tags"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/categories"

[[menu.nav]]
  name = "Papers"
  weight = -80 
  identifier = "papers"
  url = "/page/papers"

[[menu.nav]]
  name = "About"
  weight = -80 
  identifier = "about"
  url = "/page/about"

# -----------------------------------------------------------------------
# Morphism theme footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/irfansharif/"

[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-twitter fa-2x'></i> "
  weight = -90 
  identifier = "twitter"
  url = "https://twitter.com/irfansharifm"
