baseURL = "https://irfansharif.io/blog/"
canonifyURLs = "true"
languageCode = "en-us"
theme = "central"
title = "irfansharif.io"
footnoteReturnLinkContents = "⤻" # Options: ↩

[permalinks]
  posts = "/:title/"
  page = "/:slug/"

# Theme variables.
[params]
  description = "Notes on system design for young(er) bloods."

[markup]
  defaultMarkdownHandler = "blackfriday"

# vim: ts=2 sw=2 et ft=conf
