name = "meta"
license = "MIT"
licenselink = "https://github.com/irfansharif/meta/blob/master/LICENSE.md"
description = "A minimalist blog theme using Tufte-css, inspired by shawnohare/hugo-tufte"
homepage = "http://github.com/irfansharif/meta"
tags = ["blog", "tufte", "minimal"]
features = ["math", "tufte-css", "tufte"]
min_version = 0.15

[author]
  name = "Irfan Sharif"
  homepage = "http://irfansharif.io"
