#!/bin/sh

set -euxo pipefail

git submodule update --init --recursive
hugo -d ../public
git checkout gh-pages
rm -r *
cp -r ../public/* .
rm -r ../public
git add --all
git commit --amend --no-edit
git push -f
git checkout master
git clean -fdx
git submodule update --init --recursive
